# Generated by Django 5.0.8 on 2025-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-is_recommended', '-created_at'], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Отметить как рекомендуемый промокод (показывается с особым бейджем)', verbose_name='BoltPromo рекомендует'),
        ),
    ]
