# Generated by Django 5.0.8 on 2025-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_promocode_options_promocode_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='Правовая информация (особенно для финансовых услуг)', verbose_name='Дисклеймер'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='fine_print',
            field=models.TextField(blank=True, help_text='Мелкий шрифт - ограничения и условия', verbose_name='Условия использования'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='long_description',
            field=models.TextField(blank=True, help_text='Детальное описание предложения для модального окна', verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='offer_type',
            field=models.CharField(choices=[('coupon', 'Промокод'), ('deal', 'Скидка'), ('financial', 'Финансовая услуга'), ('cashback', 'Кэшбэк')], default='coupon', help_text='Промокод - копируется код, Скидка - прямая ссылка, Финансовая услуга - CTA с дисклеймером, Кэшбэк - бейдж и переход', max_length=20, verbose_name='Тип предложения'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='steps',
            field=models.TextField(blank=True, help_text='Пошаговая инструкция по использованию (каждый шаг с новой строки или JSON)', verbose_name='Шаги активации'),
        ),
    ]
