# Generated by Django 5.0.8 on 2025-08-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promocode_disclaimer_promocode_fine_print_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('page', models.CharField(blank=True, help_text='С какой страницы отправлено сообщение', max_length=200, verbose_name='Страница отправки')),
                ('user_agent', models.TextField(blank=True, help_text='Информация о браузере пользователя', verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('is_processed', models.BooleanField(default=False, help_text='Отметьте, когда ответите на сообщение', verbose_name='Обработано')),
                ('is_spam', models.BooleanField(default=False, help_text='Отметить как спам', verbose_name='Спам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created_at'],
            },
        ),
    ]
