# Generated by Django 5.0.8 on 2025-08-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-is_recommended', '-is_hot', '-created_at'], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.RenameField(
            model_name='promocode',
            old_name='views',
            new_name='views_count',
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_label',
            field=models.CharField(blank=True, help_text='Например: "Скидка 20%", "Бесплатная доставка", "Кэшбэк 5%"', max_length=100, verbose_name='Метка скидки'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.CharField(choices=[('faq', 'FAQ'), ('privacy', 'Политика конфиденциальности'), ('terms', 'Пользовательское соглашение'), ('about', 'О проекте')], max_length=20, unique=True, verbose_name='URL'),
        ),
    ]
