# Generated by Django 4.2.17 on 2025-09-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_discount_label_and_fix_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(blank=True, default='Подробнее', max_length=50, verbose_name='Текст кнопки'),
        ),
    ]