# Generated by Django 4.2.17 on 2025-09-30 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_banner_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('banner', models.ImageField(upload_to='showcases/', verbose_name='Баннер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Витрина',
                'verbose_name_plural': 'Витрины',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-is_recommended', '-is_hot', '-created_at'], 'verbose_name': 'РџСЂРѕРјРѕРєРѕРґ', 'verbose_name_plural': 'РџСЂРѕРјРѕРєРѕРґС‹'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='РџРѕСЂСЏРґРѕРє'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='РџСЂРѕРјРѕРєРѕРґ'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='offer_type',
            field=models.CharField(choices=[('coupon', 'РџСЂРѕРјРѕРєРѕРґ'), ('deal', 'РЎРєРёРґРєР°'), ('financial', 'Финансовая услуга'), ('cashback', 'Кэшбэк')], default='coupon', help_text='Промокод - копируется код, Скидка - прямая ссылка, Финансовая услуга - CTA с дисклеймером, Кэшбэк - бейдж и переход', max_length=20, verbose_name='Тип предложения'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='ShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_items', to='core.promocode', verbose_name='Промокод')),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.showcase', verbose_name='Витрина')),
            ],
            options={
                'verbose_name': 'Элемент витрины',
                'verbose_name_plural': 'Элементы витрины',
                'ordering': ['position', 'id'],
                'unique_together': {('showcase', 'promocode')},
            },
        ),
    ]
