# Generated by Django 4.2.17 on 2025-10-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adminactionlog_sitesettings_event_dailyagg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('favicon_src', models.ImageField(blank=True, help_text='PNG/ICO, рекомендуется 512×512px (будет конвертирован в .ico)', null=True, upload_to='site_assets/favicon/', verbose_name='Favicon (исходник)')),
                ('og_default', models.ImageField(blank=True, help_text='1200×630px для Open Graph', null=True, upload_to='site_assets/og/', verbose_name='OG изображение по умолчанию')),
                ('twitter_default', models.ImageField(blank=True, help_text='1200×600px (опционально, если отличается от OG)', null=True, upload_to='site_assets/twitter/', verbose_name='Twitter Card изображение')),
                ('apple_touch_icon_src', models.ImageField(blank=True, help_text='PNG, рекомендуется 180×180px или больше', null=True, upload_to='site_assets/apple/', verbose_name='Apple Touch Icon (исходник)')),
                ('pwa_icon_src', models.ImageField(blank=True, help_text='PNG, рекомендуется 512×512px (будут созданы 192, 512, maskable)', null=True, upload_to='site_assets/pwa/', verbose_name='PWA иконка (исходник)')),
                ('safari_pinned_svg', models.FileField(blank=True, help_text='Монохромный SVG для Safari', null=True, upload_to='site_assets/safari/', verbose_name='Safari Pinned Tab SVG')),
                ('theme_color', models.CharField(default='#0b1020', help_text='Цвет темы браузера (hex формат)', max_length=7, verbose_name='Theme Color')),
                ('background_color', models.CharField(default='#0b1020', help_text='Фоновый цвет для splash screen', max_length=7, verbose_name='Background Color')),
                ('favicon_ico_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к favicon.ico')),
                ('favicon_16_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к favicon-16.png')),
                ('favicon_32_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к favicon-32.png')),
                ('apple_touch_icon_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к apple-touch-icon.png')),
                ('pwa_192_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к icon-192.png')),
                ('pwa_512_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к icon-512.png')),
                ('pwa_maskable_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к maskable-icon-512.png')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя генерация')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Медиа-ресурсы сайта',
                'verbose_name_plural': 'Медиа-ресурсы сайта',
            },
        ),
    ]
