# Generated by Django 4.2.17 on 2025-10-02 22:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_site_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержимое'),
        ),
    ]
