# Generated by Django 5.0.8 on 2025-10-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_staticpage_content'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', 'expires_at'], name='core_promoc_is_acti_84a1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['store', 'is_active'], name='core_promoc_store_i_9c4140_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_hot', 'is_active'], name='core_promoc_is_hot_58531e_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['-created_at'], name='core_promoc_created_374846_idx'),
        ),
    ]
