# Generated by Django 5.0.8 on 2025-10-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_popular_ordering_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyagg',
            name='core_dailya_promo_date_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='promocode',
            name='core_promoc_hot_rec_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='promocode',
            name='core_promoc_active_exp_created_idx',
        ),
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 800x600px. Если не загружено, будет использоваться десктопное изображение.', null=True, upload_to='banners/mobile/', verbose_name='Изображение (Мобилка)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Изображение (Десктоп)'),
        ),
    ]
