# Generated by Django 5.0.8 on 2025-10-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_mobile_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Рекомендуемый размер: 1200x380px. Для десктопной версии сайта.', upload_to='banners/', verbose_name='Изображение (Десктоп)'),
        ),
    ]
