# Generated by Django 5.0.8 on 2025-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_banner_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'name'], name='idx_category_active'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at'], name='idx_contact_created'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['ip_address', 'created_at'], name='idx_contact_ip_date'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_processed', 'is_spam', '-created_at'], name='idx_contact_status'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', '-rating', 'name'], name='idx_store_active_rating'),
        ),
    ]
