# Generated by Django 5.0.8 on 2025-10-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_critical_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('', '--- Без иконки ---'), ('ShoppingBag', 'ShoppingBag - Покупки'), ('Store', 'Store - Магазин'), ('Shirt', 'Shirt - Одежда'), ('Footprints', 'Footprints - Обувь'), ('Smartphone', 'Smartphone - Телефон'), ('Laptop', 'Laptop - Ноутбук'), ('Monitor', 'Monitor - Монитор'), ('Tv', 'Tv - ТВ/Техника'), ('Home', 'Home - Дом'), ('Sofa', 'Sofa - Мебель'), ('Utensils', 'Utensils - Еда/Рестораны'), ('Coffee', 'Coffee - Кафе'), ('Pizza', 'Pizza - Пицца'), ('Apple', 'Apple - Продукты'), ('Heart', 'Heart - Здоровье/Красота'), ('Sparkles', 'Sparkles - Косметика'), ('Dumbbell', 'Dumbbell - Спорт/Фитнес'), ('Bike', 'Bike - Велосипед'), ('Car', 'Car - Авто'), ('Plane', 'Plane - Авиа/Путешествия'), ('Palmtree', 'Palmtree - Туризм'), ('Hotel', 'Hotel - Отель'), ('Briefcase', 'Briefcase - Бизнес/Офис'), ('GraduationCap', 'GraduationCap - Образование'), ('BookOpen', 'BookOpen - Книги'), ('Music', 'Music - Музыка'), ('Gamepad2', 'Gamepad2 - Игры'), ('Film', 'Film - Кино'), ('Camera', 'Camera - Фото'), ('Baby', 'Baby - Детское'), ('Gem', 'Gem - Украшения'), ('Gift', 'Gift - Подарки'), ('Flower', 'Flower - Цветы'), ('PawPrint', 'PawPrint - Животные/Зоотовары'), ('TreePine', 'TreePine - Сад/Растения'), ('Hammer', 'Hammer - Инструменты/Ремонт'), ('Zap', 'Zap - Электроника'), ('Wifi', 'Wifi - Интернет/Связь'), ('CreditCard', 'CreditCard - Финансы/Банки'), ('Wallet', 'Wallet - Кошелек'), ('Ticket', 'Ticket - Билеты/События'), ('Package', 'Package - Посылки/Доставка'), ('Tag', 'Tag - Общее')], help_text='Выберите иконку из списка популярных Lucide Icons', max_length=50, verbose_name='Иконка (Lucide)'),
        ),
    ]
