# Generated by Django 5.0.8 on 2025-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_icon_choices_to_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ga_measurement_id',
            field=models.CharField(blank=True, default='', help_text='Например: G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics 4 ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_html_body',
            field=models.TextField(blank=True, default='', verbose_name='Google HTML файл (содержимое)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_html_filename',
            field=models.CharField(blank=True, default='', help_text='Например: google1234567890abcdef.html', max_length=255, verbose_name='Google HTML файл (имя)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_verification_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Google верификация (meta content)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_html_body',
            field=models.TextField(blank=True, default='', verbose_name='Яндекс HTML файл (содержимое)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_html_filename',
            field=models.CharField(blank=True, default='', help_text='Например: yandex_1234567890abcdef.html', max_length=255, verbose_name='Яндекс HTML файл (имя)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, default='', help_text='Например: 12345678', max_length=50, verbose_name='Яндекс.Метрика ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_verification_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Яндекс верификация (meta content)'),
        ),
    ]
